model:
  type: unet_tiny
  channels: 3
  base_channels: 32
  depth: 2
data:
  source: cifar10
  root: data
  channels: 3
  height: 32
  width: 32
  download: false
training:
  batch_size: 32
  epochs: 1
  num_batches: null
  log_every: 100
diffusion:
  num_timesteps: 1000
  beta_schedule: cosine
  prediction_type: eps
  snr_weighting: false
  snr_transform: snr
  loss_threshold: null
  time_embed_dim: 128
optim:
  lr: 1.0e-4
  weight_decay: 0.0
spectral:
  enabled: false
  normalize: true
  weighting: none
  freq_equalized_noise: false
  freq_attention: false
sampling:
  sampler_type: ddim
