# @extends configs/benchmark_synthetic_large_base.yaml
data:
  family: texture
spectral:
  enabled: true
  learnable: true
  condition: time
  weighting: bandpass
  apply_to: [output]
  per_block: true