model:
  type: unet_tiny
  channels: 3
  base_channels: 16
  depth: 1

data:
  source: synthetic
  family: texture
  channels: 3
  height: 16
  width: 16

training:
  batch_size: 64
  epochs: 3
  num_batches: 15
  log_every: 5

optim:
  lr: 2.0e-4
  weight_decay: 0.0

diffusion:
  num_timesteps: 200
  beta_schedule: linear
  prediction_type: eps
  snr_weighting: false
  snr_transform: snr
  loss_threshold: null
  time_embed_dim: 64

loss:
  reduction: mean
  spectral_weighting: none
  bandpass_inner: 0.1
  bandpass_outer: 0.6

spectral:
  enabled: true
  learnable: true
  condition: time
  weighting: bandpass
  apply_to: [output]
  per_block: true
  normalize: true

sampling:
  enabled: false
  sampler_type: ddpm
  num_samples: 8
  num_steps: 20

evaluation:
  reference_dir: null
  use_fid: false
  image_size: null
