model:
  type: baseline
  channels: 3
  base_channels: 16
  depth: 1

data:
  source: synthetic
  channels: 3
  height: 8
  width: 8

training:
  batch_size: 4
  epochs: 1
  num_batches: 5
  log_every: 1

optim:
  lr: 1.0e-4
  weight_decay: 0.0

diffusion:
  num_timesteps: 10
  beta_schedule: linear
  prediction_type: eps
  snr_weighting: false
  snr_transform: snr
  loss_threshold: null
  time_embed_dim: 64

loss:
  reduction: mean
  spectral_weighting: none
  bandpass_inner: 0.1
  bandpass_outer: 0.6

spectral:
  enabled: false
  normalize: true
  weighting: none
  freq_equalized_noise: false
  freq_attention: false
  apply_to: [input]
  per_block: false
  bandpass_inner: 0.1
  bandpass_outer: 0.6

sampling:
  enabled: false
  sampler_type: ddpm
  num_samples: 4
  num_steps: 10

evaluation:
  reference_dir: null
  use_fid: false
  image_size: null
