model:
  type: unet_tiny
  channels: 3
  base_channels: 32
  depth: 2

data:
  source: cifar10
  root: data
  channels: 3
  height: 32
  width: 32
  download: true

training:
  batch_size: 64
  epochs: 3
  num_batches: 10
  log_every: 10

optim:
  lr: 2.0e-4
  weight_decay: 0.0

diffusion:
  num_timesteps: 1000
  beta_schedule: cosine
  prediction_type: eps
  snr_weighting: false
  snr_transform: snr
  loss_threshold: null
  time_embed_dim: 128

loss:
  reduction: mean
  spectral_weighting: none
  bandpass_inner: 0.1
  bandpass_outer: 0.6

spectral:
  enabled: false
  normalize: true
  weighting: none
  freq_equalized_noise: false
  freq_attention: false
  apply_to: [input, output]
  per_block: false
  bandpass_inner: 0.1
  bandpass_outer: 0.6

sampling:
  enabled: true
  sampler_type: ddpm
  num_samples: 16
  num_steps: 50

initialization:
  strategy: default
  scale: 0.02

evaluation:
  reference_dir: null
  use_fid: false
  image_size: null
