data:
  channels: 3
  download: false
  height: 32
  root: data
  source: cifar10
  width: 32
diffusion:
  beta_schedule: cosine
  loss_threshold: null
  num_timesteps: 1000
  prediction_type: eps
  snr_transform: snr
  snr_weighting: false
  time_embed_dim: 128
evaluation:
  image_size: null
  reference_dir: null
  use_fid: false
loss:
  bandpass_inner: 0.1
  bandpass_outer: 0.6
  reduction: mean
  spectral_weighting: none
model:
  base_channels: 32
  channels: 3
  depth: 2
  type: unet_tiny
optim:
  lr: 0.0001
  weight_decay: 0.0
sampling:
  enabled: false
  num_samples: 16
  num_steps: 1000
  sampler_type: dpm_solver++
spectral:
  apply_to:
  - input
  - output
  bandpass_inner: 0.1
  bandpass_outer: 0.6
  enabled: true
  freq_attention: true
  freq_equalized_noise: true
  normalize: true
  per_block: false
  weighting: radial
training:
  batch_size: 32
  epochs: 1
  log_every: 100
  num_batches: null
