name: Run Full Report

on:
  workflow_dispatch:
    inputs:
      report_script:
        description: "Script to execute (relative path). Defaults to scripts/run_full_report_32x32.sh"
        required: false
        default: "scripts/run_full_report_32x32.sh"

jobs:
  run-report:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run report pipeline
        id: run_report
        shell: bash
        run: |
          set -euo pipefail
          script_input="${{ github.event.inputs.report_script }}"
          if [[ -z "${script_input}" ]]; then
            script_input="scripts/run_full_report_32x32.sh"
          fi
          if [[ ! -x "${script_input}" ]]; then
            chmod +x "${script_input}"
          fi
          echo "Running report script: ${script_input}"
          bash "${script_input}"

          # Locate the freshest report directory created by the script.
          report_dir="$(ls -td results/full_report_* 2>/dev/null | head -n1 || true)"
          if [[ -z "${report_dir}" ]]; then
            echo "No report directory found under results/. Failing the job."
            exit 1
          fi

          echo "report_dir=${report_dir}" >> "$GITHUB_OUTPUT"
          echo "artifact_name=$(basename "${report_dir}")" >> "$GITHUB_OUTPUT"

      - name: Upload report artifacts
        if: steps.run_report.outputs.report_dir != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.run_report.outputs.artifact_name }}
          path: ${{ steps.run_report.outputs.report_dir }}
